### ISSUE TITLE
No output on log level DEBUG and below

### ISSUE THREAD

**Issue by mupfdev** [picojs/picolog#1]
INFO and above work perfectly fine. Any ideas what the problem might be?

**Comment by ghost** [comment]
The examples run correctly. Make sure you're using 

```C
void plog_set_level(plog_level_t level);
```
Only those messages of equal or higher priority than (severity) than this value will be logged.

**Comment by mupfdev** [comment]
Thanks, that fixed it. I thought it is enought to set the log level in plog_add_stream.
